name: Scan do Horusec

on: [push]

jobs:
  horusec-security:
    name: horusec
    runs-on: ubuntu-latest
    steps:
    - name: Checando código
      uses: actions/checkout@v2
      with: # Necessário quando habilitado o autores de commit
        fetch-depth: 0
    - name: Running Horusec Security
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
        horusec start -p="./" -e="true"
